services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: fastapi dev main.py --host 0.0.0.0 --port 8080

  mongodb:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongodb:/data/db

